addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"      % "0.9.29")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"      % "2.4.2")
addSbtPlugin("com.eed3si9n"      % "sbt-projectmatrix" % "0.8.0")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"      % "3.9.4")
addSbtPlugin("com.github.gseitz" % "sbt-release"       % "1.0.13")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"           % "2.0.1")
addSbtPlugin("com.dwijnand"      % "sbt-travisci"      % "1.2.0")
